### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by ajmeese7**
Nothing major. The code looks very repetitive but otherwise seems fine to me. Seems like the switching of videos only works sometimes because it wants to pause the videos on the side but I'll work on fixing that in the future if I have more time.

### CODE REVIEW

**Comment by tonypan2000** [comment]
"This branch has conflicts that must be resolved" How do I fix that?

**Comment by TonyLianLong** [comment]
@ajmeese7 You may need to update the repository to its latest version.
@tonypan2000 I fixed the conflicts and merged the pull request.

**Comment by ajmeese7** [comment]
What do you mean? @TonyLianLong

**Comment by TonyLianLong** [comment]
@ajmeese7 Your README.md has conflicts with this repository. That means you modified the file before fetching from the upstream and new changes were made with the upstream. You can do a fetch before making modifications.

**Pull request merged**
